#!/bin/bash

# 🌍 Script de Configuración de Entornos
# Este script ayuda a configurar los archivos de entorno de manera interactiva

set -e

echo "🌍 Configuración de Entornos para Supabase"
echo "==========================================="
echo ""

# Función para validar URL
validate_url() {
    if [[ $1 =~ ^https://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        return 0
    else
        return 1
    fi
}

# Función para validar JWT
validate_jwt() {
    if [[ $1 =~ ^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$ ]]; then
        return 0
    else
        return 1
    fi
}

# Verificar si .env.local ya existe
if [ -f ".env.local" ]; then
    echo "⚠️  El archivo .env.local ya existe."
    read -p "¿Deseas sobrescribirlo? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Operación cancelada."
        exit 1
    fi
fi

echo "📝 Ingresa tus credenciales de Supabase:"
echo "   (Puedes encontrarlas en: https://supabase.com/dashboard > Settings > API)"
echo ""

# Solicitar URL de Supabase
while true; do
    read -p "🔗 URL del proyecto Supabase: " SUPABASE_URL
    if validate_url "$SUPABASE_URL"; then
        break
    else
        echo "❌ URL inválida. Debe tener formato: https://tu-proyecto.supabase.co"
    fi
done

# Solicitar clave anónima
while true; do
    read -p "🔑 Clave anónima (anon key): " SUPABASE_ANON_KEY
    if validate_jwt "$SUPABASE_ANON_KEY"; then
        break
    else
        echo "❌ Clave inválida. Debe ser un JWT válido."
    fi
done

# Preguntar por clave de servicio (opcional)
read -p "🔐 Clave de servicio (opcional, presiona Enter para omitir): " SUPABASE_SERVICE_KEY

echo ""
echo "📄 Creando archivo .env.local..."

# Crear archivo .env.local
cat > .env.local << EOF
# Supabase Configuration
# Generated by setup-env.sh on $(date)

# Your Supabase project URL
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL

# Your Supabase anon/public key
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

EOF

# Agregar clave de servicio si se proporcionó
if [ ! -z "$SUPABASE_SERVICE_KEY" ]; then
    echo "# Supabase service role key (server-side only)" >> .env.local
    echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_KEY" >> .env.local
    echo "" >> .env.local
fi

# Agregar configuraciones adicionales
cat >> .env.local << EOF
# Application settings
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_DEBUG_MODE=true
EOF

echo "✅ Archivo .env.local creado exitosamente!"
echo ""
echo "🚀 Próximos pasos:"
echo "   1. Ejecuta: npm run dev"
echo "   2. Ve a: http://localhost:3000"
echo "   3. Configura tu base de datos con: supabase-schema.sql"
echo ""
echo "📚 Para más información, lee: ENVIRONMENT-SETUP.md"
echo ""
echo "🎉 ¡Configuración completada!"